import Head from "next/head";
import TodoList from "../components/TodoList";
import axios from "axios";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoList data={data} />
    </div>
  );
}

export async function getStaticProps() {
  const todoList = await axios.get("https://ozy.ilearn.mn/v1/todo");
  return await {
    props: { data: todoList.data.data },
  };
}
